### ISSUE TITLE
paths are closed even though no "z" is given

### ISSUE THREAD

**Issue by FlorianLudwig** [saschagehlich/pixi-svg-graphics#2]
The path:

d="M -12,610 L 230,112 L 469,897 L 795,533"

will be rendered like
![screenshot from 2015-08-13 13-09-31](https://cloud.githubusercontent.com/assets/432263/9248506/9819d336-41bc-11e5-85c2-9f8bfa4989d4.png)

but should look like

![screenshot from 2015-08-13 13-09-44](https://cloud.githubusercontent.com/assets/432263/9248507/99b326d4-41bc-11e5-82a7-aa5b93f001bb.png)

**Comment by jwdunn1** [comment]
I ran into this same issue. By default, PIXI draws closed paths, and the code was written for that. For open paths, a command can be added just after the moveTo() at line 255: this._graphics.graphicsData[this._graphics.graphicsData.length-1].shape.closed=false
Then add to the "case 'z'": (around line 348)
this._graphics.graphicsData[this._graphics.graphicsData.length-1].shape.closed=true

The tests I ran passed.

**Comment by FlorianLudwig** [comment]
@jwdunn1 Sounds good.  Where is your fork ;) ?

**Comment by rdsilver** [comment]
@FlorianLudwig Did you ever figure this out?

**Comment by FlorianLudwig** [comment]
@rdsilver actually we did a bigger rewrite of the original code: https://github.com/GreyRook/pixi-svg-graphics for several reasons. If you have similar problems there as well feel free to open an issue.

The api is different so its not a drop-in replacement.

**Comment by rdsilver** [comment]
@FlorianLudwig What version of pixi are you using?

**Comment by FlorianLudwig** [comment]
Currently it is still only tested on pixi 3 but it will be ported to 4 in
the foreseeable future.

Patches are welcome ;)

**Comment by rdsilver** [comment]
@FlorianLudwig Could you test if this SVG renders correctly using your fork?
https://maps.westfield.io/cms/components/peoplemovertype/446_1_wf-WTC-Icon_TemplateA_Elevators-01.svg?api_key=QHkV9FttXgovron9ZqTGnwyMGlnJ564m

When I used it appeared like this: http://i.imgur.com/QzkvaDy.png

If you give me your venmo name i'll give you moola for helping out :)

**Comment by saschagehlich** [comment]
This has been fixed in 1.0.0 thanks to @FlorianLudwig's fork which has been integrated in the original repository :)
